In [ ]:
pip install pymongo

In [ ]:
# To access the database
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://<db_username>:<db_password>@cluster0.13icold.mongodb.net/?appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [ ]:
pip install pandas

In [8]:
# Load the dataset
import pandas as pd

df = pd.read_csv('animals.csv')
df.head()

,organization,type,gender,name,link,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Hong Kong Rabit Society,Rabbit,F,Vico,https://siuyeo.ng/hkaad20251225,NaN,NaN,NaN
1,Hong Kong Dog Rescue,Dog,F,Gladys,https://siuyeo.ng/hkaad20251224,NaN,NaN,NaN
2,SPCA,Dog,M,浩浩,https://siuyeo.ng/hkaad20251223,NaN,NaN,NaN
3,Paws United Charity,Dog,F,Bridgette,https://siuyeo.ng/hkaad20251222,NaN,NaN,NaN
4,HKSCDA,Cat,F,Donki,https://siuyeo.ng/hkaad20251221,NaN,NaN,NaN

In [10]:
# Deal with missing values
type(df['Unnamed: 5'].loc[0])

float

In [12]:
df = df.astype(object).where(pd.notna(df), None)

In [13]:
df.head()

,organization,type,gender,name,link,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Hong Kong Rabit Society,Rabbit,F,Vico,https://siuyeo.ng/hkaad20251225,None,None,None
1,Hong Kong Dog Rescue,Dog,F,Gladys,https://siuyeo.ng/hkaad20251224,None,None,None
2,SPCA,Dog,M,浩浩,https://siuyeo.ng/hkaad20251223,None,None,None
3,Paws United Charity,Dog,F,Bridgette,https://siuyeo.ng/hkaad20251222,None,None,None
4,HKSCDA,Cat,F,Donki,https://siuyeo.ng/hkaad20251221,None,None,None

In [14]:
list_of_dicts = df.to_dict(orient='records')

In [15]:
list_of_dicts

[{'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'F',
  'name': 'Vico',
  'link': 'https://siuyeo.ng/hkaad20251225',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Gladys',
  'link': 'https://siuyeo.ng/hkaad20251224',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Dog',
  'gender': 'M',
  'name': '浩浩',
  'link': 'https://siuyeo.ng/hkaad20251223',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Bridgette',
  'link': 'https://siuyeo.ng/hkaad20251222',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Donki',
  'link': 'https://siuyeo.ng/hkaad20251221',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Saturday',
  'link': 'https://siuyeo.ng/hkaad20251220',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Lulu',
  'link': 'https://siuyeo.ng/hkaad20251219',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Turtle',
  'gender': None,
  'name': '紅豆',
  'link': 'https://siuyeo.ng/hkaad20251218',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'F',
  'name': 'Zespri',
  'link': 'https://siuyeo.ng/hkaad20251217',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Wolfie',
  'link': 'https://siuyeo.ng/hkaad20251216',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Sailor',
  'link': 'https://siuyeo.ng/hkadd20251215',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Letty',
  'link': 'https://siuyeo.ng/hkaad20251214',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'M',
  'name': '錦小龍',
  'link': 'https://siuyeo.ng/hkaad20251213',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Wednesday',
  'link': 'https://siuyeo.ng/hkaad20251212',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Mimi',
  'link': 'https://siuyeo.ng/hkaad20251211',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Snake',
  'gender': None,
  'name': 'AC08',
  'link': 'https://siuyeo.ng/hkaad20251210',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'F',
  'name': 'Mofu',
  'link': 'https://siuyeo.ng/hkaad20251209',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Gallant',
  'link': 'https://siuyeo.ng/hkaad20251208',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Cat',
  'gender': 'M',
  'name': 'Wavey',
  'link': 'https://siuyeo.ng/hkaad20251207',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Holly',
  'link': 'https://siuyeo.ng/hkaad20251206',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'WINWIN',
  'link': 'https://siuyeo.ng/hkadd20251205',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Monday',
  'link': 'https://siuyeo.ng/hkaad20251204',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Cat',
  'gender': 'M',
  'name': '亞黃',
  'link': 'https://siuyeo.ng/hkaad20251203',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Frog',
  'gender': None,
  'name': '蛋黃妹',
  'link': 'https://siuyeo.ng/hkaad20251202',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'M',
  'name': 'Reo',
  'link': 'https://siuyeo.ng/hkaad20251201',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Justin',
  'link': 'https://siuyeo.ng/hkaad20251130',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Charlotte',
  'link': 'https://siuyeo.ng/hkaad20251129',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Aaron',
  'link': 'https://siuyeo.ng/hkaad20251128',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'F',
  'name': '周生生',
  'link': 'https://siuyeo.ng/hkaad20251127',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Sugar',
  'link': 'https://siuyeo.ng/hkaad20251126',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Billy',
  'link': 'https://siuyeo.ng/hkaad20251125',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Snake',
  'gender': None,
  'name': '阿橙',
  'link': 'https://siuyeo.ng/hkaad20251124',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'F',
  'name': 'Lana',
  'link': 'https://siuyeo.ng/hkaad20251123',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Simone',
  'link': 'https://siuyeo.ng/hkaad20251122',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Dog',
  'gender': 'M',
  'name': '貝貝',
  'link': 'https://siuyeo.ng/hkaad20251121',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Bridgette',
  'link': 'https://siuyeo.ng/hkaad20251120',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'F',
  'name': '金三妹',
  'link': 'https://siuyeo.ng/hkaad20251119',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Doddie',
  'link': 'https://siuyeo.ng/hkaad20251118',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Cat',
  'gender': 'M',
  'name': '喱喱',
  'link': 'https://siuyeo.ng/hkaad20251117',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Turtle',
  'gender': None,
  'name': '紅豆',
  'link': 'https://siuyeo.ng/hkaad20251116',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'F',
  'name': 'Koaki',
  'link': 'https://siuyeo.ng/hkaad20251115',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Nino',
  'link': 'https://siuyeo.ng/hkaad20251114',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Mia',
  'link': 'https://siuyeo.ng/hkaad20251113',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Rachel',
  'link': 'https://siuyeo.ng/hkaad20251112',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'F',
  'name': '金大妹',
  'link': 'https://siuyeo.ng/hkaad20251111',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Cody',
  'link': 'https://siuyeo.ng/hkaad20251110',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Cat',
  'gender': 'M',
  'name': '亞蝦',
  'link': 'https://siuyeo.ng/hkaad20251109',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Frog',
  'gender': None,
  'name': '蛋黃妹',
  'link': 'https://siuyeo.ng/hkaad20251108',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'F',
  'name': 'Joni',
  'link': 'https://siuyeo.ng/hkaad20251107',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Todd',
  'link': 'https://siuyeo.ng/hkaad20251106',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Cat',
  'gender': 'M',
  'name': '峰峰',
  'link': 'https://siuyeo.ng/hkaad20251105',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Kylie',
  'link': 'https://siuyeo.ng/hkaad20251104',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'M',
  'name': '樂樂',
  'link': 'https://siuyeo.ng/hkaad20251103',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Wasabi',
  'link': 'https://siuyeo.ng/hkaad20251102',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Dog',
  'gender': 'F',
  'name': '香蕉',
  'link': 'https://siuyeo.ng/hkaad20251101',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Snake',
  'gender': None,
  'name': '阿橙',
  'link': 'https://siuyeo.ng/hkaad20251031',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'F',
  'name': 'Yama',
  'link': 'https://siuyeo.ng/hkaad20251030',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Mercury',
  'link': 'https://siuyeo.ng/hkaad20251029',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Spongebob',
  'link': 'https://siuyeo.ng/hkaad20251028',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Sienna',
  'link': 'https://siuyeo.ng/hkaad20251027',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'F',
  'name': '古心怡',
  'link': 'https://siuyeo.ng/hkaad20251026',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Yan Yan',
  'link': 'https://siuyeo.ng/hkaad20251025',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Dog',
  'gender': 'F',
  'name': '乖乖',
  'link': 'https://siuyeo.ng/hkaad20251024',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Turtle',
  'gender': None,
  'name': '紅豆',
  'link': 'https://siuyeo.ng/hkaad20251023',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'F',
  'name': 'Ciwi',
  'link': 'https://siuyeo.ng/hkaad20251022',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Tumble',
  'link': 'https://siuyeo.ng/hkaad20251021',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Moana',
  'link': 'https://siuyeo.ng/hkaad20251020',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Bridgette',
  'link': 'https://siuyeo.ng/hkaad20251019',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'M',
  'name': '細佬',
  'link': 'https://siuyeo.ng/hkaad20251018',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Mei Mei',
  'link': 'https://siuyeo.ng/hkaad20251017',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Cat',
  'gender': 'M',
  'name': 'Winson',
  'link': 'https://siuyeo.ng/hkaad20251016',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Frog',
  'gender': None,
  'name': '蛋黃妹',
  'link': 'https://siuyeo.ng/hkaad20251015',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'M',
  'name': 'Vegas',
  'link': 'https://siuyeo.ng/hkaad20251014',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Erin',
  'link': 'https://siuyeo.ng/hkaad20251013',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Dog',
  'gender': 'M',
  'name': '小邁',
  'link': 'https://siuyeo.ng/hkaad20251012',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Swan',
  'link': 'https://siuyeo.ng/hkaad20251011',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'F',
  'name': '水飯飯',
  'link': 'https://siuyeo.ng/hkaad20251010',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'F',
  'name': 'Z',
  'link': 'https://siuyeo.ng/hkaad20251009',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Dog',
  'gender': 'M',
  'name': '叻仔',
  'link': 'https://siuyeo.ng/hkaad20251008',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Snake',
  'gender': None,
  'name': '阿橙',
  'link': 'https://siuyeo.ng/hkaad20251007',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'M',
  'name': 'Gin',
  'link': 'https://siuyeo.ng/hkaad20251006',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Unity',
  'link': 'https://siuyeo.ng/hkaad20251005',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Dog',
  'gender': 'F',
  'name': '琑琑',
  'link': 'https://siuyeo.ng/hkaad20251004',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Bose',
  'link': 'https://siuyeo.ng/hkaad20251003',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'F',
  'name': '美細妹',
  'link': 'https://siuyeo.ng/hkaad20251002',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'M',
  'name': 'Tab',
  'link': 'https://siuyeo.ng/hkaad20251001',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Windsor',
  'link': 'https://siuyeo.ng/hkaad20250930',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Turtle',
  'gender': None,
  'name': '紅豆',
  'link': 'https://siuyeo.ng/hkaad20250929',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'F',
  'name': 'Gulu',
  'link': 'https://siuyeo.ng/hkaad20250928',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Viva',
  'link': 'https://siuyeo.ng/hkaad20250927',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Dorma',
  'link': 'https://siuyeo.ng/hkaad20250926',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'M',
  'name': 'George',
  'link': 'https://siuyeo.ng/hkaad20250925',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'F',
  'name': '美家姐',
  'link': 'https://siuyeo.ng/hkaad20250924',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SAA',
  'type': 'Cat',
  'gender': 'M',
  'name': 'Gin',
  'link': 'https://siuyeo.ng/hkaad20250923',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKAAC',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Bear Bear',
  'link': 'https://siuyeo.ng/hkaad20250922',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKHERP',
  'type': 'Frog',
  'gender': None,
  'name': '蛋黃妹',
  'link': 'https://siuyeo.ng/hkaad20250921',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Rabit Society',
  'type': 'Rabbit',
  'gender': 'M',
  'name': 'Goma',
  'link': 'https://siuyeo.ng/hkaad20250920',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Hong Kong Dog Rescue',
  'type': 'Dog',
  'gender': 'M',
  'name': 'Theo',
  'link': 'https://siuyeo.ng/hkaad20250919',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'SPCA',
  'type': 'Dog',
  'gender': 'M',
  'name': '樂諾',
  'link': 'https://siuyeo.ng/hkaad20250918',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'Paws United Charity',
  'type': 'Dog',
  'gender': 'F',
  'name': 'Sammy',
  'link': 'https://siuyeo.ng/hkaad20250917',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},
 {'organization': 'HKSCDA',
  'type': 'Cat',
  'gender': 'F',
  'name': '王梅子',
  'link': 'https://siuyeo.ng/hkaad20250916',
  'Unnamed: 5': None,
  'Unnamed: 6': None,
  'Unnamed: 7': None},

In [18]:
db = client['animalsdb']

In [22]:
db.list_collection_names()

['animals']

In [21]:
# Create a new collection
collection = db.create_collection("animals")

In [23]:
collection.insert_many(list_of_dicts)

InsertManyResult([ObjectId('694d47ea48279e585de9a5fd'), ObjectId('694d47ea48279e585de9a5fe'), ObjectId('694d47ea48279e585de9a5ff'), ObjectId('694d47ea48279e585de9a600'), ObjectId('694d47ea48279e585de9a601'), ObjectId('694d47ea48279e585de9a602'), ObjectId('694d47ea48279e585de9a603'), ObjectId('694d47ea48279e585de9a604'), ObjectId('694d47ea48279e585de9a605'), ObjectId('694d47ea48279e585de9a606'), ObjectId('694d47ea48279e585de9a607'), ObjectId('694d47ea48279e585de9a608'), ObjectId('694d47ea48279e585de9a609'), ObjectId('694d47ea48279e585de9a60a'), ObjectId('694d47ea48279e585de9a60b'), ObjectId('694d47ea48279e585de9a60c'), ObjectId('694d47ea48279e585de9a60d'), ObjectId('694d47ea48279e585de9a60e'), ObjectId('694d47ea48279e585de9a60f'), ObjectId('694d47ea48279e585de9a610'), ObjectId('694d47ea48279e585de9a611'), ObjectId('694d47ea48279e585de9a612'), ObjectId('694d47ea48279e585de9a613'), ObjectId('694d47ea48279e585de9a614'), ObjectId('694d47ea48279e585de9a615'), ObjectId('694d47ea48279e585de9a616'), ObjectId('694d47ea48279e585de9a617'), ObjectId('694d47ea48279e585de9a618'), ObjectId('694d47ea48279e585de9a619'), ObjectId('694d47ea48279e585de9a61a'), ObjectId('694d47ea48279e585de9a61b'), ObjectId('694d47ea48279e585de9a61c'), ObjectId('694d47ea48279e585de9a61d'), ObjectId('694d47ea48279e585de9a61e'), ObjectId('694d47ea48279e585de9a61f'), ObjectId('694d47ea48279e585de9a620'), ObjectId('694d47ea48279e585de9a621'), ObjectId('694d47ea48279e585de9a622'), ObjectId('694d47ea48279e585de9a623'), ObjectId('694d47ea48279e585de9a624'), ObjectId('694d47ea48279e585de9a625'), ObjectId('694d47ea48279e585de9a626'), ObjectId('694d47ea48279e585de9a627'), ObjectId('694d47ea48279e585de9a628'), ObjectId('694d47ea48279e585de9a629'), ObjectId('694d47ea48279e585de9a62a'), ObjectId('694d47ea48279e585de9a62b'), ObjectId('694d47ea48279e585de9a62c'), ObjectId('694d47ea48279e585de9a62d'), ObjectId('694d47ea48279e585de9a62e'), ObjectId('694d47ea48279e585de9a62f'), ObjectId('694d47ea48279e585de9a630'), ObjectId('694d47ea48279e585de9a631'), ObjectId('694d47ea48279e585de9a632'), ObjectId('694d47ea48279e585de9a633'), ObjectId('694d47ea48279e585de9a634'), ObjectId('694d47ea48279e585de9a635'), ObjectId('694d47ea48279e585de9a636'), ObjectId('694d47ea48279e585de9a637'), ObjectId('694d47ea48279e585de9a638'), ObjectId('694d47ea48279e585de9a639'), ObjectId('694d47ea48279e585de9a63a'), ObjectId('694d47ea48279e585de9a63b'), ObjectId('694d47ea48279e585de9a63c'), ObjectId('694d47ea48279e585de9a63d'), ObjectId('694d47ea48279e585de9a63e'), ObjectId('694d47ea48279e585de9a63f'), ObjectId('694d47ea48279e585de9a640'), ObjectId('694d47ea48279e585de9a641'), ObjectId('694d47ea48279e585de9a642'), ObjectId('694d47ea48279e585de9a643'), ObjectId('694d47ea48279e585de9a644'), ObjectId('694d47ea48279e585de9a645'), ObjectId('694d47ea48279e585de9a646'), ObjectId('694d47ea48279e585de9a647'), ObjectId('694d47ea48279e585de9a648'), ObjectId('694d47ea48279e585de9a649'), ObjectId('694d47ea48279e585de9a64a'), ObjectId('694d47ea48279e585de9a64b'), ObjectId('694d47ea48279e585de9a64c'), ObjectId('694d47ea48279e585de9a64d'), ObjectId('694d47ea48279e585de9a64e'), ObjectId('694d47ea48279e585de9a64f'), ObjectId('694d47ea48279e585de9a650'), ObjectId('694d47ea48279e585de9a651'), ObjectId('694d47ea48279e585de9a652'), ObjectId('694d47ea48279e585de9a653'), ObjectId('694d47ea48279e585de9a654'), ObjectId('694d47ea48279e585de9a655'), ObjectId('694d47ea48279e585de9a656'), ObjectId('694d47ea48279e585de9a657'), ObjectId('694d47ea48279e585de9a658'), ObjectId('694d47ea48279e585de9a659'), ObjectId('694d47ea48279e585de9a65a'), ObjectId('694d47ea48279e585de9a65b'), ObjectId('694d47ea48279e585de9a65c'), ObjectId('694d47ea48279e585de9a65d'), ObjectId('694d47ea48279e585de9a65e'), ObjectId('694d47ea48279e585de9a65f'), ObjectId('694d47ea48279e585de9a660'), ObjectId('694d47ea48279e585de9a661'), ObjectId('694d47ea48279e585de9a662'), ObjectId('694d47ea48279e585de9a663'), ObjectId('694d47ea48279e585de9a664'), ObjectId('694d47ea48279e585de9a665'), ObjectId('694d47ea48279e585de9a666'), ObjectId('694d47ea48279e585de9a667'), ObjectId('694d47ea48279e585de9a668'), ObjectId('694d47ea48279e585de9a669'), ObjectId('694d47ea48279e585de9a66a'), ObjectId('694d47ea48279e585de9a66b'), ObjectId('694d47ea48279e585de9a66c'), ObjectId('694d47ea48279e585de9a66d'), ObjectId('694d47ea48279e585de9a66e'), ObjectId('694d47ea48279e585de9a66f'), ObjectId('694d47ea48279e585de9a670'), ObjectId('694d47ea48279e585de9a671'), ObjectId('694d47ea48279e585de9a672'), ObjectId('694d47ea48279e585de9a673'), ObjectId('694d47ea48279e585de9a674'), ObjectId('694d47ea48279e585de9a675'), ObjectId('694d47ea48279e585de9a676'), ObjectId('694d47ea48279e585de9a677'), ObjectId('694d47ea48279e585de9a678'), ObjectId('694d47ea48279e585de9a679'), ObjectId('694d47ea48279e585de9a67a'), ObjectId('694d47ea48279e585de9a67b'), ObjectId('694d47ea48279e585de9a67c'), ObjectId('694d47ea48279e585de9a67d'), ObjectId('694d47ea48279e585de9a67e'), ObjectId('694d47ea48279e585de9a67f'), ObjectId('694d47ea48279e585de9a680'), ObjectId('694d47ea48279e585de9a681'), ObjectId('694d47ea48279e585de9a682'), ObjectId('694d47ea48279e585de9a683'), ObjectId('694d47ea48279e585de9a684'), ObjectId('694d47ea48279e585de9a685'), ObjectId('694d47ea48279e585de9a686'), ObjectId('694d47ea48279e585de9a687'), ObjectId('694d47ea48279e585de9a688'), ObjectId('694d47ea48279e585de9a689'), ObjectId('694d47ea48279e585de9a68a'), ObjectId('694d47ea48279e585de9a68b'), ObjectId('694d47ea48279e585de9a68c'), ObjectId('694d47ea48279e585de9a68d'), ObjectId('694d47ea48279e585de9a68e'), ObjectId('694d47ea48279e585de9a68f'), ObjectId('694d47ea48279e585de9a690'), ObjectId('694d47ea48279e585de9a691'), ObjectId('694d47ea48279e585de9a692'), ObjectId('694d47ea48279e585de9a693'), ObjectId('694d47ea48279e585de9a694'), ObjectId('694d47ea48279e585de9a695'), ObjectId('694d47ea48279e585de9a696'), ObjectId('694d47ea48279e585de9a697'), ObjectId('694d47ea48279e585de9a698'), ObjectId('694d47ea48279e585de9a699'), ObjectId('694d47ea48279e585de9a69a'), ObjectId('694d47ea48279e585de9a69b'), ObjectId('694d47ea48279e585de9a69c'), ObjectId('694d47ea48279e585de9a69d'), ObjectId('694d47ea48279e585de9a69e'), ObjectId('694d47ea48279e585de9a69f'), ObjectId('694d47ea48279e585de9a6a0'), ObjectId('694d47ea48279e585de9a6a1'), ObjectId('694d47ea48279e585de9a6a2'), ObjectId('694d47ea48279e585de9a6a3'), ObjectId('694d47ea48279e585de9a6a4'), ObjectId('694d47ea48279e585de9a6a5'), ObjectId('694d47ea48279e585de9a6a6'), ObjectId('694d47ea48279e585de9a6a7'), ObjectId('694d47ea48279e585de9a6a8'), ObjectId('694d47ea48279e585de9a6a9'), ObjectId('694d47ea48279e585de9a6aa'), ObjectId('694d47ea48279e585de9a6ab'), ObjectId('694d47ea48279e585de9a6ac'), ObjectId('694d47ea48279e585de9a6ad'), ObjectId('694d47ea48279e585de9a6ae'), ObjectId('694d47ea48279e585de9a6af'), ObjectId('694d47ea48279e585de9a6b0'), ObjectId('694d47ea48279e585de9a6b1'), ObjectId('694d47ea48279e585de9a6b2'), ObjectId('694d47ea48279e585de9a6b3'), ObjectId('694d47ea48279e585de9a6b4'), ObjectId('694d47ea48279e585de9a6b5'), ObjectId('694d47ea48279e585de9a6b6'), ObjectId('694d47ea48279e585de9a6b7'), ObjectId('694d47ea48279e585de9a6b8'), ObjectId('694d47ea48279e585de9a6b9'), ObjectId('694d47ea48279e585de9a6ba'), ObjectId('694d47ea48279e585de9a6bb'), ObjectId('694d47ea48279e585de9a6bc'), ObjectId('694d47ea48279e585de9a6bd'), ObjectId('694d47ea48279e585de9a6be'), ObjectId('694d47ea48279e585de9a6bf'), ObjectId('694d47ea48279e585de9a6c0'), ObjectId('694d47ea48279e585de9a6c1'), ObjectId('694d47ea48279e585de9a6c2'), ObjectId('694d47ea48279e585de9a6c3'), ObjectId('694d47ea48279e585de9a6c4'), ObjectId('694d47ea48279e585de9a6c5'), ObjectId('694d47ea48279e585de9a6c6'), ObjectId('694d47ea48279e585de9a6c7'), ObjectId('694d47ea48279e585de9a6c8'), ObjectId('694d47ea48279e585de9a6c9'), ObjectId('694d47ea48279e585de9a6ca'), ObjectId('694d47ea48279e585de9a6cb'), ObjectId('694d47ea48279e585de9a6cc'), ObjectId('694d47ea48279e585de9a6cd'), ObjectId('694d47ea48279e585de9a6ce'), ObjectId('694d47ea48279e585de9a6cf'), ObjectId('694d47ea48279e585de9a6d0'), ObjectId('694d47ea48279e585de9a6d1'), ObjectId('694d47ea48279e585de9a6d2'), ObjectId('694d47ea48279e585de9a6d3'), ObjectId('694d47ea48279e585de9a6d4'), ObjectId('694d47ea48279e585de9a6d5'), ObjectId('694d47ea48279e585de9a6d6'), ObjectId('694d47ea48279e585de9a6d7'), ObjectId('694d47ea48279e585de9a6d8'), ObjectId('694d47ea48279e585de9a6d9'), ObjectId('694d47ea48279e585de9a6da'), ObjectId('694d47ea48279e585de9a6db'), ObjectId('694d47ea48279e585de9a6dc'), ObjectId('694d47ea48279e585de9a6dd'), ObjectId('694d47ea48279e585de9a6de'), ObjectId('694d47ea48279e585de9a6df'), ObjectId('694d47ea48279e585de9a6e0'), ObjectId('694d47ea48279e585de9a6e1'), ObjectId('694d47ea48279e585de9a6e2'), ObjectId('694d47ea48279e585de9a6e3'), ObjectId('694d47ea48279e585de9a6e4'), ObjectId('694d47ea48279e585de9a6e5'), ObjectId('694d47ea48279e585de9a6e6'), ObjectId('694d47ea48279e585de9a6e7'), ObjectId('694d47ea48279e585de9a6e8'), ObjectId('694d47ea48279e585de9a6e9'), ObjectId('694d47ea48279e585de9a6ea'), ObjectId('694d47ea48279e585de9a6eb'), ObjectId('694d47ea48279e585de9a6ec'), ObjectId('694d47ea48279e585de9a6ed'), ObjectId('694d47ea48279e585de9a6ee'), ObjectId('694d47ea48279e585de9a6ef'), ObjectId('694d47ea48279e585de9a6f0'), ObjectId('694d47ea48279e585de9a6f1'), ObjectId('694d47ea48279e585de9a6f2'), ObjectId('694d47ea48279e585de9a6f3'), ObjectId('694d47ea48279e585de9a6f4'), ObjectId('694d47ea48279e585de9a6f5'), ObjectId('694d47ea48279e585de9a6f6'), ObjectId('694d47ea48279e585de9a6f7'), ObjectId('694d47ea48279e585de9a6f8'), ObjectId('694d47ea48279e585de9a6f9'), ObjectId('694d47ea48279e585de9a6fa'), ObjectId('694d47ea48279e585de9a6fb'), ObjectId('694d47ea48279e585de9a6fc'), ObjectId('694d47ea48279e585de9a6fd'), ObjectId('694d47ea48279e585de9a6fe'), ObjectId('694d47ea48279e585de9a6ff'), ObjectId('694d47ea48279e585de9a700'), ObjectId('694d47ea48279e585de9a701'), ObjectId('694d47ea48279e585de9a702'), ObjectId('694d47ea48279e585de9a703'), ObjectId('694d47ea48279e585de9a704'), ObjectId('694d47ea48279e585de9a705'), ObjectId('694d47ea48279e585de9a706'), ObjectId('694d47ea48279e585de9a707'), ObjectId('694d47ea48279e585de9a708'), ObjectId('694d47ea48279e585de9a709'), ObjectId('694d47ea48279e585de9a70a'), ObjectId('694d47ea48279e585de9a70b'), ObjectId('694d47ea48279e585de9a70c'), ObjectId('694d47ea48279e585de9a70d'), ObjectId('694d47ea48279e585de9a70e'), ObjectId('694d47ea48279e585de9a70f'), ObjectId('694d47ea48279e585de9a710'), ObjectId('694d47ea48279e585de9a711'), ObjectId('694d47ea48279e585de9a712'), ObjectId('694d47ea48279e585de9a713'), ObjectId('694d47ea48279e585de9a714'), ObjectId('694d47ea48279e585de9a715'), ObjectId('694d47ea48279e585de9a716'), ObjectId('694d47ea48279e585de9a717'), ObjectId('694d47ea48279e585de9a718'), ObjectId('694d47ea48279e585de9a719'), ObjectId('694d47ea48279e585de9a71a'), ObjectId('694d47ea48279e585de9a71b'), ObjectId('694d47ea48279e585de9a71c'), ObjectId('694d47ea48279e585de9a71d'), ObjectId('694d47ea48279e585de9a71e'), ObjectId('694d47ea48279e585de9a71f'), ObjectId('694d47ea48279e585de9a720'), ObjectId('694d47ea48279e585de9a721'), ObjectId('694d47ea48279e585de9a722'), ObjectId('694d47ea48279e585de9a723'), ObjectId('694d47ea48279e585de9a724'), ObjectId('694d47ea48279e585de9a725'), ObjectId('694d47ea48279e585de9a726'), ObjectId('694d47ea48279e585de9a727'), ObjectId('694d47ea48279e585de9a728'), ObjectId('694d47ea48279e585de9a729'), ObjectId('694d47ea48279e585de9a72a'), ObjectId('694d47ea48279e585de9a72b'), ObjectId('694d47ea48279e585de9a72c'), ObjectId('694d47ea48279e585de9a72d'), ObjectId('694d47ea48279e585de9a72e'), ObjectId('694d47ea48279e585de9a72f'), ObjectId('694d47ea48279e585de9a730'), ObjectId('694d47ea48279e585de9a731'), ObjectId('694d47ea48279e585de9a732'), ObjectId('694d47ea48279e585de9a733'), ObjectId('694d47ea48279e585de9a734'), ObjectId('694d47ea48279e585de9a735'), ObjectId('694d47ea48279e585de9a736'), ObjectId('694d47ea48279e585de9a737'), ObjectId('694d47ea48279e585de9a738'), ObjectId('694d47ea48279e585de9a739'), ObjectId('694d47ea48279e585de9a73a'), ObjectId('694d47ea48279e585de9a73b'), ObjectId('694d47ea48279e585de9a73c'), ObjectId('694d47ea48279e585de9a73d'), ObjectId('694d47ea48279e585de9a73e'), ObjectId('694d47ea48279e585de9a73f'), ObjectId('694d47ea48279e585de9a740'), ObjectId('694d47ea48279e585de9a741'), ObjectId('694d47ea48279e585de9a742'), ObjectId('694d47ea48279e585de9a743'), ObjectId('694d47ea48279e585de9a744'), ObjectId('694d47ea48279e585de9a745'), ObjectId('694d47ea48279e585de9a746'), ObjectId('694d47ea48279e585de9a747'), ObjectId('694d47ea48279e585de9a748'), ObjectId('694d47ea48279e585de9a749'), ObjectId('694d47ea48279e585de9a74a'), ObjectId('694d47ea48279e585de9a74b'), ObjectId('694d47ea48279e585de9a74c'), ObjectId('694d47ea48279e585de9a74d'), ObjectId('694d47ea48279e585de9a74e'), ObjectId('694d47ea48279e585de9a74f'), ObjectId('694d47ea48279e585de9a750'), ObjectId('694d47ea48279e585de9a751'), ObjectId('694d47ea48279e585de9a752'), ObjectId('694d47ea48279e585de9a753'), ObjectId('694d47ea48279e585de9a754'), ObjectId('694d47ea48279e585de9a755'), ObjectId('694d47ea48279e585de9a756'), ObjectId('694d47ea48279e585de9a757'), ObjectId('694d47ea48279e585de9a758'), ObjectId('694d47ea48279e585de9a759'), ObjectId('694d47ea48279e585de9a75a'), ObjectId('694d47ea48279e585de9a75b'), ObjectId('694d47ea48279e585de9a75c'), ObjectId('694d47ea48279e585de9a75d'), ObjectId('694d47ea48279e585de9a75e'), ObjectId('694d47ea48279e585de9a75f'), ObjectId('694d47ea48279e585de9a760'), ObjectId('694d47ea48279e585de9a761'), ObjectId('694d47ea48279e585de9a762'), ObjectId('694d47ea48279e585de9a763'), ObjectId('694d47ea48279e585de9a764'), ObjectId('694d47ea48279e585de9a765'), ObjectId('694d47ea48279e585de9a766'), ObjectId('694d47ea48279e585de9a767'), ObjectId('694d47ea48279e585de9a768'), ObjectId('694d47ea48279e585de9a769'), ObjectId('694d47ea48279e585de9a76a'), ObjectId('694d47ea48279e585de9a76b'), ObjectId('694d47ea48279e585de9a76c'), ObjectId('694d47ea48279e585de9a76d'), ObjectId('694d47ea48279e585de9a76e'), ObjectId('694d47ea48279e585de9a76f'), ObjectId('694d47ea48279e585de9a770'), ObjectId('694d47ea48279e585de9a771'), ObjectId('694d47ea48279e585de9a772'), ObjectId('694d47ea48279e585de9a773'), ObjectId('694d47ea48279e585de9a774'), ObjectId('694d47ea48279e585de9a775'), ObjectId('694d47ea48279e585de9a776'), ObjectId('694d47ea48279e585de9a777'), ObjectId('694d47ea48279e585de9a778'), ObjectId('694d47ea48279e585de9a779'), ObjectId('694d47ea48279e585de9a77a'), ObjectId('694d47ea48279e585de9a77b'), ObjectId('694d47ea48279e585de9a77c'), ObjectId('694d47ea48279e585de9a77d'), ObjectId('694d47ea48279e585de9a77e'), ObjectId('694d47ea48279e585de9a77f'), ObjectId('694d47ea48279e585de9a780'), ObjectId('694d47ea48279e585de9a781'), ObjectId('694d47ea48279e585de9a782'), ObjectId('694d47ea48279e585de9a783'), ObjectId('694d47ea48279e585de9a784'), ObjectId('694d47ea48279e585de9a785'), ObjectId('694d47ea48279e585de9a786'), ObjectId('694d47ea48279e585de9a787'), ObjectId('694d47ea48279e585de9a788'), ObjectId('694d47ea48279e585de9a789'), ObjectId('694d47ea48279e585de9a78a'), ObjectId('694d47ea48279e585de9a78b'), ObjectId('694d47ea48279e585de9a78c'), ObjectId('694d47ea48279e585de9a78d'), ObjectId('694d47ea48279e585de9a78e'), ObjectId('694d47ea48279e585de9a78f'), ObjectId('694d47ea48279e585de9a790'), ObjectId('694d47ea48279e585de9a791'), ObjectId('694d47ea48279e585de9a792'), ObjectId('694d47ea48279e585de9a793'), ObjectId('694d47ea48279e585de9a794'), ObjectId('694d47ea48279e585de9a795'), ObjectId('694d47ea48279e585de9a796'), ObjectId('694d47ea48279e585de9a797'), ObjectId('694d47ea48279e585de9a798'), ObjectId('694d47ea48279e585de9a799'), ObjectId('694d47ea48279e585de9a79a'), ObjectId('694d47ea48279e585de9a79b'), ObjectId('694d47ea48279e585de9a79c'), ObjectId('694d47ea48279e585de9a79d'), ObjectId('694d47ea48279e585de9a79e'), ObjectId('694d47ea48279e585de9a79f'), ObjectId('694d47ea48279e585de9a7a0'), ObjectId('694d47ea48279e585de9a7a1'), ObjectId('694d47ea48279e585de9a7a2'), ObjectId('694d47ea48279e585de9a7a3'), ObjectId('694d47ea48279e585de9a7a4'), ObjectId('694d47ea48279e585de9a7a5'), ObjectId('694d47ea48279e585de9a7a6'), ObjectId('694d47ea48279e585de9a7a7'), ObjectId('694d47ea48279e585de9a7a8'), ObjectId('694d47ea48279e585de9a7a9'), ObjectId('694d47ea48279e585de9a7aa'), ObjectId('694d47ea48279e585de9a7ab'), ObjectId('694d47ea48279e585de9a7ac'), ObjectId('694d47ea48279e585de9a7ad'), ObjectId('694d47ea48279e585de9a7ae'), ObjectId('694d47ea48279e585de9a7af'), ObjectId('694d47ea48279e585de9a7b0'), ObjectId('694d47ea48279e585de9a7b1'), ObjectId('694d47ea48279e585de9a7b2'), ObjectId('694d47ea48279e585de9a7b3'), ObjectId('694d47ea48279e585de9a7b4'), ObjectId('694d47ea48279e585de9a7b5'), ObjectId('694d47ea48279e585de9a7b6'), ObjectId('694d47ea48279e585de9a7b7'), ObjectId('694d47ea48279e585de9a7b8'), ObjectId('694d47ea48279e585de9a7b9'), ObjectId('694d47ea48279e585de9a7ba'), ObjectId('694d47ea48279e585de9a7bb'), ObjectId('694d47ea48279e585de9a7bc'), ObjectId('694d47ea48279e585de9a7bd'), ObjectId('694d47ea48279e585de9a7be'), ObjectId('694d47ea48279e585de9a7bf'), ObjectId('694d47ea48279e585de9a7c0'), ObjectId('694d47ea48279e585de9a7c1'), ObjectId('694d47ea48279e585de9a7c2'), ObjectId('694d47ea48279e585de9a7c3'), ObjectId('694d47ea48279e585de9a7c4'), ObjectId('694d47ea48279e585de9a7c5'), ObjectId('694d47ea48279e585de9a7c6'), ObjectId('694d47ea48279e585de9a7c7'), ObjectId('694d47ea48279e585de9a7c8'), ObjectId('694d47ea48279e585de9a7c9'), ObjectId('694d47ea48279e585de9a7ca'), ObjectId('694d47ea48279e585de9a7cb'), ObjectId('694d47ea48279e585de9a7cc'), ObjectId('694d47ea48279e585de9a7cd'), ObjectId('694d47ea48279e585de9a7ce'), ObjectId('694d47ea48279e585de9a7cf'), ObjectId('694d47ea48279e585de9a7d0'), ObjectId('694d47ea48279e585de9a7d1'), ObjectId('694d47ea48279e585de9a7d2'), ObjectId('694d47ea48279e585de9a7d3'), ObjectId('694d47ea48279e585de9a7d4'), ObjectId('694d47ea48279e585de9a7d5'), ObjectId('694d47ea48279e585de9a7d6'), ObjectId('694d47ea48279e585de9a7d7'), ObjectId('694d47ea48279e585de9a7d8'), ObjectId('694d47ea48279e585de9a7d9'), ObjectId('694d47ea48279e585de9a7da'), ObjectId('694d47ea48279e585de9a7db'), ObjectId('694d47ea48279e585de9a7dc'), ObjectId('694d47ea48279e585de9a7dd'), ObjectId('694d47ea48279e585de9a7de'), ObjectId('694d47ea48279e585de9a7df'), ObjectId('694d47ea48279e585de9a7e0'), ObjectId('694d47ea48279e585de9a7e1'), ObjectId('694d47ea48279e585de9a7e2'), ObjectId('694d47ea48279e585de9a7e3'), ObjectId('694d47ea48279e585de9a7e4'), ObjectId('694d47ea48279e585de9a7e5'), ObjectId('694d47ea48279e585de9a7e6'), ObjectId('694d47ea48279e585de9a7e7'), ObjectId('694d47ea48279e585de9a7e8'), ObjectId('694d47ea48279e585de9a7e9'), ObjectId('694d47ea48279e585de9a7ea'), ObjectId('694d47ea48279e585de9a7eb'), ObjectId('694d47ea48279e585de9a7ec'), ObjectId('694d47ea48279e585de9a7ed'), ObjectId('694d47ea48279e585de9a7ee'), ObjectId('694d47ea48279e585de9a7ef'), ObjectId('694d47ea48279e585de9a7f0'), ObjectId('694d47ea48279e585de9a7f1'), ObjectId('694d47ea48279e585de9a7f2'), ObjectId('694d47ea48279e585de9a7f3'), ObjectId('694d47ea48279e585de9a7f4'), ObjectId('694d47ea48279e585de9a7f5'), ObjectId('694d47ea48279e585de9a7f6'), ObjectId('694d47ea48279e585de9a7f7'), ObjectId('694d47ea48279e585de9a7f8'), ObjectId('694d47ea48279e585de9a7f9'), ObjectId('694d47ea48279e585de9a7fa'), ObjectId('694d47ea48279e585de9a7fb'), ObjectId('694d47ea48279e585de9a7fc'), ObjectId('694d47ea48279e585de9a7fd'), ObjectId('694d47ea48279e585de9a7fe'), ObjectId('694d47ea48279e585de9a7ff'), ObjectId('694d47ea48279e585de9a800'), ObjectId('694d47ea48279e585de9a801'), ObjectId('694d47ea48279e585de9a802'), ObjectId('694d47ea48279e585de9a803'), ObjectId('694d47ea48279e585de9a804'), ObjectId('694d47ea48279e585de9a805'), ObjectId('694d47ea48279e585de9a806'), ObjectId('694d47ea48279e585de9a807'), ObjectId('694d47ea48279e585de9a808'), ObjectId('694d47ea48279e585de9a809'), ObjectId('694d47ea48279e585de9a8

In [24]:
collection.count_documents({})

2071